"""Initial migration

Revision ID: 8839c5a0b56c
Revises:
Create Date: 2026-06-20 23:18:16.233780

NOTE on bootstrap order: this chain does NOT create the application schema.
KAEOS bootstraps its ~175 tables via Base.metadata.create_all (init_db), and
every migration here is a delta on top of that. A fresh database is therefore:

    1. init_db()             (as the OWNER role - creates current-model schema)
    2. alembic upgrade head  (as the OWNER role - installs RLS, roles, deltas)

Because create_all produces the CURRENT model schema, additive migrations may
find their table/column already present — each one checks and skips, so the
chain is safe to run in either order relative to create_all.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8839c5a0b56c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    if sa.inspect(op.get_bind()).has_table('rule_embeddings'):
        return  # already created by init_db()/create_all
    op.create_table('rule_embeddings',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_rule_embeddings_tenant_id'), 'rule_embeddings', ['tenant_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_embeddings_tenant_id'), table_name='rule_embeddings')
    op.drop_table('rule_embeddings')
    # ### end Alembic commands ###
