"""S6 M2.1 — the HR V1 router split into one sub-router per sub-domain.

The committed OpenAPI baseline (``scripts/openapi_surface_snapshot.py --check``)
already pins the method+path SET, every operationId, and every schema. What it
does NOT pin is the ORDER the routes are mounted in, because it sorts. Route
order is match precedence, so a split that regroups endpoints by sub-domain can
change which handler answers a request while leaving the baseline green.

These tests pin the order, and pin the module-level names that code outside the
package still imports from ``app.hr.api.v1.router``.
"""
import re

import app.hr.api.v1.router as hr_router_module
from app.hr.api.v1.router import router as hr_router

# The pre-split router declared this many operations (75 hand-written + the 3
# generated by make_department_workflow_router).
EXPECTED_ROUTE_COUNT = 78

# Every module that is allowed to own an HR route. The assembler itself owns
# only the two HITL endpoints (external code monkeypatches
# ``app.hr.api.v1.router.record_security_event`` to reach them), and the shared
# factory owns the three generated workflow endpoints.
EXPECTED_OWNING_MODULES = {
    "app.core.department_endpoints",
    "app.hr.api.v1.router",
    "app.hr.api.v1.routers.benefits",
    "app.hr.api.v1.routers.compensation",
    "app.hr.api.v1.routers.compliance",
    "app.hr.api.v1.routers.connectors",
    "app.hr.api.v1.routers.dashboard",
    "app.hr.api.v1.routers.employee_documents",
    "app.hr.api.v1.routers.employee_relations",
    "app.hr.api.v1.routers.employees",
    "app.hr.api.v1.routers.interviews",
    "app.hr.api.v1.routers.learning",
    "app.hr.api.v1.routers.metrics",
    "app.hr.api.v1.routers.onboarding",
    "app.hr.api.v1.routers.payroll",
    "app.hr.api.v1.routers.performance",
    "app.hr.api.v1.routers.recruiting",
    "app.hr.api.v1.routers.timesheets",
    "app.hr.api.v1.routers.workflows",
    "app.hr.api.v1.routers.workforce_planning",
}


def _flatten(router, prefix=""):
    """(method, path, endpoint) in mount order, on old and new FastAPI alike.

    FastAPI >= 0.140 registers ``include_router`` as a lazy ``_IncludedRouter``
    proxy instead of copying the routes in, so a plain ``router.routes`` walk
    sees the proxy and none of its routes. Recurse through ``original_router``
    (re-applying the prefix the include carried) when the proxy is present, and
    fall back to the flat 0.115 behaviour when it is not.
    """
    out = []
    for route in router.routes:
        included = getattr(route, "original_router", None)
        if included is not None:
            out.extend(_flatten(included, prefix + getattr(route.include_context, "prefix", "")))
            continue
        for method in sorted(getattr(route, "methods", ()) or ()):
            out.append((method, prefix + route.path, route.endpoint))
    return out


ROUTES = _flatten(hr_router)
PAIRS = [(m, p) for m, p, _ in ROUTES]


def _index(method, path):
    assert (method, path) in PAIRS, f"{method} {path} is no longer mounted"
    return PAIRS.index((method, path))


def test_route_count_matches_the_pre_split_surface():
    assert len(ROUTES) == EXPECTED_ROUTE_COUNT
    assert len(set(PAIRS)) == EXPECTED_ROUTE_COUNT, "a method+path pair is mounted twice"


def test_every_sub_router_is_mounted_and_nothing_leaked_back():
    owners = {endpoint.__module__ for _, _, endpoint in ROUTES}
    assert owners == EXPECTED_OWNING_MODULES

    # The assembler keeps exactly the two HITL endpoints and nothing else.
    assembler_owned = sorted(
        p for m, p, e in ROUTES if e.__module__ == "app.hr.api.v1.router"
    )
    assert assembler_owned == ["/hr/hitl/{execution_id}/approve", "/hr/hitl/{execution_id}/reject"]


def test_literal_and_param_siblings_keep_their_pre_split_order():
    """Three sibling pairs whose order a regrouping could plausibly flip.

    The time-off pair is the one that matters most: the pre-split file declared
    ``POST /time-off-requests/{request_id}/transition`` BEFORE the collection
    ``POST /time-off-requests`` (the collection sat in a later "Entity Creation"
    section), so a naive by-sub-domain regrouping would silently reverse them.
    """
    assert _index("GET", "/hr/employees") < _index("GET", "/hr/employees/{employee_id}")
    assert (_index("GET", "/hr/employees/{employee_id}")
            < _index("POST", "/hr/employees/{employee_id}/onboarding-checkin"))

    assert (_index("POST", "/hr/time-off-requests/{request_id}/transition")
            < _index("POST", "/hr/time-off-requests"))

    assert (_index("GET", "/hr/workflows")
            < _index("POST", "/hr/workflows/{entity_type}/bulk-transition"))

    assert (_index("POST", "/hr/compliance-reports")
            < _index("POST", "/hr/compliance-reports/eeoc/generate"))


def test_no_route_is_shadowed_by_an_earlier_one():
    """Match precedence is only at risk where two paths can match one request.

    The pre-split router had zero such pairs, so this holds as an invariant
    rather than as a frozen ordering: if a later regrouping ever puts a
    param route ahead of a literal sibling it would swallow, this fails.
    """
    compiled = [(m, p, re.compile("^" + re.sub(r"{[^}]+}", "[^/]+", p) + "$")) for m, p, _ in ROUTES]
    shadowed = []
    for i, (m_a, p_a, rx_a) in enumerate(compiled):
        for m_b, p_b, _ in compiled[i + 1:]:
            if m_a == m_b and rx_a.match(re.sub(r"{[^}]+}", "x", p_b)):
                shadowed.append((p_a, p_b))
    assert shadowed == []


def test_module_still_exports_what_outside_code_imports():
    """app/main.py and tests/test_hitl_approver_integrity.py import these."""
    from app.hr.api.v1.router import HITLDecision, WORKFLOW_SPECS, hitl_approve, hitl_reject, router

    assert router is hr_router
    assert HITLDecision(approver="ignored").approver == "ignored"
    assert "time_off_request" in WORKFLOW_SPECS and "job_requisition" in WORKFLOW_SPECS

    # Both HITL endpoints must resolve record_security_event through THIS
    # module's globals: test_hitl_approver_integrity patches it there. Keeping
    # them in the assembler rather than a sub-router is what makes that work.
    assert hitl_approve.__module__ == "app.hr.api.v1.router"
    assert hitl_reject.__module__ == "app.hr.api.v1.router"
    assert hasattr(hr_router_module, "record_security_event")


def test_requisition_create_keeps_its_published_schema_name():
    """procurement declares a RequisitionCreate too, so both are published under
    module-qualified component names. The HR one pins the pre-split module path
    so an internal file move does not rename a client-visible schema."""
    from app.hr.api.v1.routers.recruiting import RequisitionCreate

    assert RequisitionCreate.__module__ == "app.hr.api.v1.router"
