"""
KAEOS Statistical Validation Generator
Generates high-volume (1000-10000) datasets to benchmark trust models.
Provides multiple model cohorts to measure implicit learning, causal accuracy, and recommendation effectiveness.
"""

import random
import logging

from sqlalchemy.ext.asyncio import AsyncSession
from app.models.intelligence_metrics import PredictionRecord, RecommendationRecord, ValidationLedger

logger = logging.getLogger(__name__)


class StatisticalGenerator:
    
    def __init__(self, seed: int = 42):
        random.seed(seed)
        
    async def generate_prediction_cohort(self, db: AsyncSession, tenant_id: str, version: str, count: int, noise_profile: float, overconfidence_bias: float):
        """
        Generates a cohort of predictions for a specific model version.
        noise_profile: 0.0 (perfect) to 1.0 (random guessing).
        overconfidence_bias: 0.0 (perfectly calibrated) to 1.0 (always 99% confident).
        """
        records = []
        for _i in range(count):
            # Base truth
            is_correct = random.random() > noise_profile
            
            # Confidence logic
            base_confidence = random.uniform(0.51, 0.95)
            # If overconfidence bias is high, and the prediction is WRONG, boost confidence to simulate bad calibration
            if not is_correct and random.random() < overconfidence_bias:
                confidence = random.uniform(0.85, 0.99)
            elif is_correct:
                confidence = random.uniform(0.70, 0.99)
            else:
                confidence = base_confidence

            record = PredictionRecord(
                tenant_id=tenant_id,
                prediction_type=random.choice(["VENDOR_RISK", "GOAL_DELAY", "ATTRITION_SPIKE", "BUDGET_OVERRUN", "SYSTEM_OUTAGE"]),
                target_entity=f"entity_{random.randint(1, 5000)}",
                confidence=confidence,
                model_version=version,
                reasoning_path="Generated by Statistical Benchmarking.",
                expected_outcome="Expected Event",
                actual_outcome="Expected Event" if is_correct else "Unexpected Event",
                status="PENDING" # Evaluated later by Learning Loop
            )
            records.append(record)
            
        db.add_all(records)
        await db.commit()
        
        outcomes = {}
        for r in records:
            outcomes[r.target_entity] = {
                "is_correct": r.actual_outcome == r.expected_outcome,
                "actual_outcome": r.actual_outcome
            }
        return outcomes

    async def generate_recommendations(self, db: AsyncSession, tenant_id: str, count: int, success_rate: float, acceptance_rate: float):
        records = []
        for _i in range(count):
            accepted = random.random() < acceptance_rate
            success = accepted and random.random() < success_rate
            
            record = RecommendationRecord(
                tenant_id=tenant_id,
                recommendation=random.choice(["Reallocate budget", "Replace Vendor", "Halt Project", "Hire Contractors"]),
                reasoning="Benchmarking Recommendation Cohort",
                model_version="v1.3",
                expected_benefit="Prevent delay",
                status="ACCEPTED" if accepted else "REJECTED",
                actual_result="Success" if success else "Failure",
                success_score=1.0 if success else (0.0 if accepted else None)
            )
            records.append(record)
        db.add_all(records)
        await db.commit()

    async def generate_simulations(self, db: AsyncSession, tenant_id: str, count: int, accuracy_rate: float):
        records = []
        for _i in range(count):
            is_accurate = random.random() < accuracy_rate
            record = ValidationLedger(
                tenant_id=tenant_id,
                validation_type="SIMULATION",
                source_event=random.choice(["MASS_RESIGNATION", "VENDOR_FAILURE", "BUDGET_CUT"]),
                predicted_state={"impact": 5, "delay_days": 30},
                actual_state={"impact": 5 if is_accurate else random.randint(6, 10), "delay_days": 30 if is_accurate else 45},
                accuracy_score=1.0 if is_accurate else random.uniform(0.1, 0.7)
            )
            records.append(record)
        db.add_all(records)
        await db.commit()

    async def generate_causal_validations(self, db: AsyncSession, tenant_id: str, count: int, precision: float):
        records = []
        for _i in range(count):
            is_accurate = random.random() < precision
            record = ValidationLedger(
                tenant_id=tenant_id,
                validation_type="CAUSAL",
                source_event="SYSTEM_FAILURE",
                predicted_state={"root_cause": "Network", "path_length": 3},
                actual_state={"root_cause": "Network" if is_accurate else "Database", "path_length": 3 if is_accurate else 5},
                accuracy_score=1.0 if is_accurate else random.uniform(0.1, 0.5)
            )
            records.append(record)
        db.add_all(records)
        await db.commit()
