"""Add SkillEmbedding

Revision ID: a3fffbddea48
Revises: 8839c5a0b56c
Create Date: 2026-06-20 23:28:23.511461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fffbddea48'
down_revision: Union[str, Sequence[str], None] = '8839c5a0b56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    if sa.inspect(op.get_bind()).has_table('skill_embeddings'):
        return  # already created by init_db()/create_all
    op.create_table('skill_embeddings',
    sa.Column('skill_db_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('skill_db_id')
    )
    op.create_index(op.f('ix_skill_embeddings_tenant_id'), 'skill_embeddings', ['tenant_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_embeddings_tenant_id'), table_name='skill_embeddings')
    op.drop_table('skill_embeddings')
    # ### end Alembic commands ###
